networks:
  grafana_network:
    external: true

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Default admin username
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default admin password
    # volumes:
    #   - grafana-data:/var/lib/grafana       # Persistent data volume

  loki:
    image: grafana/loki:latest
    container_name: loki

    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - /etc/loki
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yaml

